### ISSUE TITLE
Game: remove() function faulty

### ISSUE THREAD

**Issue by elliotda** [cs361fall2017/team1#24]
remove function has an error in it, and is causing incorrect column card removals when triggered. I'll replace the code with a tested version that works. I'll do a pull request and have another group member merge.

**Comment by thompsoq** [comment]
This sounds good товорищ.

**Comment by elliotda** [comment]
I think we should revisit this issue. By rejecting the fix, our code in master game.java-remove() is flawed. It only works correctly some of the time, therefor making it impossible to win.
