### ISSUE TITLE
Sprint 3: Issue #1, Score

### ISSUE THREAD

**Issue by thompsoq** [cs361fall2017/team1#37]
Create a score counter that rests in the bottom right hand side of the screen. The score counter will increase when a card is discarded, and will display 48 points by the time the game is finished.

**Comment by elliotda** [comment]
I think score counter was supposed to rest above the game, in statistics div. Totally open to moving it if you feel that would be better.

**Comment by elliotda** [comment]
Closing issue since this change has been implemented and merged with master
