### ISSUE TITLE
Sprint 3- Aces only Move

### ISSUE THREAD

**Issue by elliotda** [cs361fall2017/team1#43]
The move function needs to be modified to check for card value before allowing a move into an empty column. This should be easy to implement, something like, if(cardToMove.value == 14), will be inserted into move function before completing the action of moving cards to a new column.

**Comment by brodskye** [comment]
added the feature. If the card is not 14, it'll print an error.

**Comment by elliotda** [comment]
closing issue since this change has been merged to master
