### ISSUE TITLE
Create game winning screen

### ISSUE THREAD

**Issue by thompsoq** [cs361fall2017/team1#58]
Implement a winning screen when the points reach 52 or 50 respectively. Stop players from accessing other functions while the screen is up.

**Comment by brodskye** [comment]
Added html file for win screen and added implementation for it in AcesUp, including checks for winning points

**Comment by elliotda** [comment]
Reopening, AcesUpWin.html isn't generating properly. I think it has to do with the addressing. I will try to figure it out.
